# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PowerPin
                                 A QGIS plugin
 Plugin eksportuje pinezkę do serwisów typu geoportal.
 Plugin exports pin to popular geoportal-like services.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-15
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Łukasz Świątek
        email                : lukasz.swiatek1996@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import math
import os.path
import webbrowser
import json

from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import (
    QAction, QApplication, QAbstractItemView, QToolButton, QMenu
)

from qgis.gui import QgsMapTool, QgsMapToolEmitPoint, QgsRubberBand
from qgis.core import (
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsProject,
    QgsWkbTypes,
    QgsMessageLog,
    Qgis,
    QgsSettings,
)

from .resources import *
from .power_pin_dockwidget import PowerPinDockWidget

# ---------------------------------------------------------------------------
# Qt6 enum compatibility
# ---------------------------------------------------------------------------
# Qt6 (PyQt6/PySide6) przeniosło wiele enumów do klas zagnieżdżonych.
# qgis.PyQt opakowuje PyQt5 lub PyQt6 — używamy bezpiecznych aliasów.

def _qt_enum(cls, *names):
    """Zwraca pierwszy atrybut z listy jaki istnieje na klasie cls."""
    for name in names:
        val = cls
        for part in name.split('.'):
            val = getattr(val, part, None)
            if val is None:
                break
        if val is not None:
            return val
    raise AttributeError(f"Nie znaleziono enuma {names} na {cls}")

QT_USER_ROLE    = _qt_enum(Qt, 'ItemDataRole.UserRole',  'UserRole')
QT_RIGHT_DOCK   = _qt_enum(Qt, 'DockWidgetArea.RightDockWidgetArea', 'RightDockWidgetArea')
QT_CLICK_FOCUS  = _qt_enum(Qt, 'FocusPolicy.ClickFocus', 'ClickFocus')
QT_MULTI_SELECT = _qt_enum(
    QAbstractItemView,
    'SelectionMode.MultiSelection', 'MultiSelection'
)
QT_RED = QColor('red')


# ---------------------------------------------------------------------------

class PowerPin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface         = iface
        self.canvas        = iface.mapCanvas()
        self.plugin_dir    = os.path.dirname(__file__)
        self.actions       = []
        self.menu          = self.tr(u'&Power Pin PL')
        self.toolbar       = iface.addToolBar(u'PowerPin')
        self.toolbar.setObjectName(u'PowerPin')
        self.pluginIsActive     = False
        self.dockwidget         = None
        self.portals            = []
        self.split_button       = None
        self.split_button_action = None

        self.load_portals()

        # Locale
        locale      = QgsSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir, 'i18n', f'PowerPin_{locale}.qm'
        )
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Map tool do kopiowania współrzędnych
        self.clickTool = QgsMapToolEmitPoint(self.canvas)
        self.clickTool.canvasClicked.connect(self.canvasClicked)

        # Referencja do aktywnego PointTool — zapobiega przedwczesnemu
        # garbage collection, które zostawiało canvas bez obsługi zdarzeń.
        self._active_tool = None

    # ------------------------------------------------------------------
    # Portale
    # ------------------------------------------------------------------

    def load_portals(self):
        """Wczytaj konfigurację portali z pliku JSON."""
        json_path = os.path.join(self.plugin_dir, 'portals.json')
        try:
            if os.path.exists(json_path):
                with open(json_path, 'r', encoding='utf-8') as f:
                    self.portals = json.load(f)
            else:
                QgsMessageLog.logMessage(
                    f"Portals config not found: {json_path}",
                    "PowerPin", Qgis.Warning
                )
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Error loading portals: {e}", "PowerPin", Qgis.Critical
            )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def tr(self, message):
        return QCoreApplication.translate('PowerPin', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True,
                   add_to_menu=True, add_to_toolbar=True,
                   status_tip=None, whats_this=None, parent=None):
        icon   = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip  is not None: action.setStatusTip(status_tip)
        if whats_this  is not None: action.setWhatsThis(whats_this)
        if add_to_toolbar:          self.toolbar.addAction(action)
        if add_to_menu:             self.iface.addPluginToWebMenu(self.menu, action)

        self.actions.append(action)
        return action

    # ------------------------------------------------------------------
    # GUI lifecycle
    # ------------------------------------------------------------------

    def initGui(self):
        """Utwórz wpisy menu i ikony toolbara."""
        # Wyczyść poprzedni stan (ważne przy initGui wywoływanym z save_config)
        for action in self.actions:
            self.iface.removePluginWebMenu(self.tr(u'&Power Pin PL'), action)
            if self.toolbar:
                self.toolbar.removeAction(action)
        self.actions = []

        if self.split_button_action and self.toolbar:
            self.toolbar.removeAction(self.split_button_action)
            self.split_button_action = None
        if self.split_button:
            self.split_button.deleteLater()
            self.split_button = None

        # Główny przycisk ustawień
        self.main_btn = self.add_action(
            ':/plugins/power_pin/icons/map32.png',
            text=self.tr(u'Power Pin Settings'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )

        settings     = QgsSettings()
        compact_mode = settings.value("PowerPin/compact_mode", True, type=bool)

        if compact_mode:
            self.setup_compact_gui(settings)
        else:
            self.setup_expanded_gui(settings)

    def setup_expanded_gui(self, settings):
        """Klasyczny interfejs — osobny przycisk na każdy portal."""
        settings.beginGroup("PowerPin/portals")

        # Wsparcie dla starego power_pin_config.txt (jednorazowa migracja)
        legacy_path = os.path.join(self.plugin_dir, "power_pin_config.txt")
        if os.path.exists(legacy_path) and not settings.allKeys():
            try:
                with open(legacy_path, 'r', encoding='utf-8') as f:
                    for line in f:
                        parts = line.strip().split("\t")
                        if len(parts) > 1:
                            settings.setValue(parts[0], parts[1] == "ON")
            except Exception:
                pass

        for portal in self.portals:
            p_id   = portal.get('id')
            p_name = portal.get('name', p_id.capitalize())
            if settings.value(p_id, True, type=bool):
                self.add_action(
                    f':/plugins/power_pin/icons/_{p_id}.png',
                    text=self.tr(p_name),
                    callback=lambda checked, p=portal: self.put_pin(p),
                    parent=self.iface.mainWindow()
                )

        settings.endGroup()

    def setup_compact_gui(self, settings):
        """Interfejs kompaktowy — jeden split button z menu."""
        self.split_button = QToolButton()

        # Qt6: ToolButtonPopupMode przeniesione do klasy zagnieżdżonej
        try:
            self.split_button.setPopupMode(
                QToolButton.ToolButtonPopupMode.MenuButtonPopup
            )
        except AttributeError:
            self.split_button.setPopupMode(QToolButton.MenuButtonPopup)

        # ClickFocus: split button nie kradnie focusu od map tools
        self.split_button.setFocusPolicy(QT_CLICK_FOCUS)

        menu = QMenu(self.split_button)

        settings.beginGroup("PowerPin/portals")
        last_used_id  = QgsSettings().value(
            "PowerPin/last_used_portal", "google", type=str
        )
        default_action = None
        first_action   = None

        for portal in self.portals:
            p_id   = portal.get('id')
            p_name = portal.get('name', p_id.capitalize())

            if settings.value(p_id, True, type=bool):
                icon   = QIcon(f':/plugins/power_pin/icons/_{p_id}.png')
                action = QAction(icon, self.tr(p_name), self.iface.mainWindow())
                action.triggered.connect(
                    lambda checked, p=portal, a=action: self.activate_portal(p, a)
                )
                menu.addAction(action)

                if first_action is None:
                    first_action = action
                if p_id == last_used_id:
                    default_action = action

        settings.endGroup()

        if default_action is None:
            default_action = first_action

        if default_action:
            self.split_button.setDefaultAction(default_action)

        self.split_button.setMenu(menu)
        self.split_button_action = self.toolbar.addWidget(self.split_button)

    def unload(self):
        """Usuń elementy GUI z QGIS."""
        for action in self.actions:
            self.iface.removePluginWebMenu(self.tr(u'&Power Pin PL'), action)
            if self.toolbar:
                self.toolbar.removeAction(action)
        self.actions = []

        if self.split_button_action:
            self.toolbar.removeAction(self.split_button_action)
            self.split_button_action = None
        if self.split_button:
            self.split_button.deleteLater()
            self.split_button = None

        if self.toolbar:
            self.iface.mainWindow().removeToolBar(self.toolbar)
            self.toolbar.deleteLater()
            self.toolbar = None

    # ------------------------------------------------------------------
    # Portal actions
    # ------------------------------------------------------------------

    def activate_portal(self, portal_config, action):
        """Obsługa aktywacji portalu w trybie kompaktowym."""
        self.put_pin(portal_config)
        if self.split_button:
            self.split_button.setDefaultAction(action)
            self.split_button.setIcon(action.icon())
        QgsSettings().setValue("PowerPin/last_used_portal", portal_config['id'])

    def use_portal_from_list(self, item):
        """Uruchom portal wybrany dwuklikiem z listy w dockwidget."""
        p_id = item.data(QT_USER_ROLE)
        for portal in self.portals:
            if portal.get('id') == p_id:
                self.put_pin(portal)
                break

    def put_pin(self, portal_config):
        """Aktywuj map tool do wskazania lokalizacji dla danego portalu."""
        p_name = portal_config.get('name', portal_config.get('id'))

        msg = "First point is pin location"
        if portal_config.get('requires_angle', False):
            msg += ", second (drag or click again) is direction"

        self.iface.messageBar().pushMessage(
            f"Select location for {p_name}:",
            msg,
            level=Qgis.Success,
            duration=3
        )

        dynamic_mode = QgsSettings().value(
            "PowerPin/dynamic_view", True, type=bool
        )
        self._active_tool = PointTool(self.canvas, portal_config, dynamic_mode)
        self.canvas.setMapTool(self._active_tool)

    # ------------------------------------------------------------------
    # Clipboard tool
    # ------------------------------------------------------------------

    def canvasClicked(self, point):
        """Kopiuj współrzędne klikniętego punktu do schowka."""
        coords     = f"{point.y():.3f}\t{point.x():.3f}"
        actual_crs = self.canvas.mapSettings().destinationCrs().authid()
        self.canvas.unsetMapTool(self.clickTool)

        QgsMessageLog.logMessage(str(coords), 'Power Clipboard')
        QApplication.clipboard().setText(coords)

        self.iface.messageBar().pushMessage(
            "Copied to clipboard:",
            f"{coords} // {actual_crs}",
            level=Qgis.Success,
            duration=2
        )

    # ------------------------------------------------------------------
    # Config save
    # ------------------------------------------------------------------

    def save_config(self):
        """Zapisz ustawienia z dockwidgetu i odśwież GUI."""
        if not self.dockwidget:
            return

        settings = QgsSettings()

        # Checkboxy zdefiniowane w .ui — odczyt bezpośredni (brak ryzyka
        # AttributeError nawet przy przeładowaniu .ui bez zmian w Pythonie)
        settings.setValue(
            "PowerPin/dynamic_view",
            self.dockwidget.cb_dynamic_view.isChecked()
        )
        settings.setValue(
            "PowerPin/compact_mode",
            self.dockwidget.cb_compact_mode.isChecked()
        )

        settings.beginGroup("PowerPin/portals")

        # Najpierw wyłącz wszystkie
        for portal in self.portals:
            settings.setValue(portal['id'], False)

        # Włącz zaznaczone
        for item in self.dockwidget.listWidget.selectedItems():
            settings.setValue(item.data(QT_USER_ROLE), True)

        settings.endGroup()

        self.iface.messageBar().pushMessage(
            "Configuration Saved",
            "GUI Refreshed.",
            level=Qgis.Info,
            duration=3
        )

        self.initGui()

    # ------------------------------------------------------------------
    # Run / close
    # ------------------------------------------------------------------

    def onClosePlugin(self):
        if self.dockwidget:
            try:
                self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
            except TypeError:
                pass  # sygnał już odłączony
        self.pluginIsActive = False

    def run(self):
        """Otwórz dockwidget z ustawieniami."""
        # Nie blokujemy przez pluginIsActive — dock może być już widoczny
        # ale wymagać odświeżenia po zmianie map tool przez inną wtyczkę.
        self.pluginIsActive = True

        if self.dockwidget is None:
            self.dockwidget = PowerPinDockWidget()
            # Sygnały podłączamy tylko raz przy tworzeniu widgetu.
            self.dockwidget.pushButton.clicked.connect(self.save_config)

            # itemClicked zamiast itemDoubleClicked:
            # Po utracie focusu przez dock (inna wtyczka aktywowała map tool)
            # pierwsze kliknięcie w listę przywraca focus (FocusEvent),
            # a dopiero drugie docierało jako itemDoubleClicked — efekt:
            # nic się nie działo. Z itemClicked wystarczy jedno kliknięcie.
            self.dockwidget.listWidget.itemClicked.connect(
                self.use_portal_from_list
            )
            self.dockwidget.listWidget.setToolTip(
                self.tr(
                    "Click to use portal / Kliknij aby użyć portalu"
                )
            )
            self.dockwidget.pushButton_3.clicked.connect(
                lambda: webbrowser.open_new(
                    'http://github.com/Rzezimioszek/QGIS-power-pin'
                )
            )
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

        # Wypełnij listę portali
        self.dockwidget.listWidget.clear()
        settings = QgsSettings()

        self.dockwidget.cb_dynamic_view.setChecked(
            settings.value("PowerPin/dynamic_view", True, type=bool)
        )
        self.dockwidget.cb_compact_mode.setChecked(
            settings.value("PowerPin/compact_mode", True, type=bool)
        )

        settings.beginGroup("PowerPin/portals")
        self.dockwidget.listWidget.setSelectionMode(QT_MULTI_SELECT)

        for portal in self.portals:
            p_id   = portal.get('id')
            p_name = portal.get('name', p_id)

            item = QtWidgets.QListWidgetItem(p_name)
            item.setData(QT_USER_ROLE, p_id)
            self.dockwidget.listWidget.addItem(item)
            item.setSelected(settings.value(p_id, True, type=bool))

        settings.endGroup()

        self.iface.addDockWidget(QT_RIGHT_DOCK, self.dockwidget)
        self.dockwidget.show()


# ---------------------------------------------------------------------------

class PointTool(QgsMapTool):
    """Map tool do wskazywania lokalizacji i otwierania URL portalu."""

    def __init__(self, canvas, portal_config, dynamic_mode=True):
        super().__init__(canvas)
        self.canvas        = canvas
        self.portal_config = portal_config
        self.dynamic_mode  = dynamic_mode
        self.pressed       = False
        self.has_line      = False
        self.point0        = None
        self.point1        = None

        self.rb = QgsRubberBand(canvas, QgsWkbTypes.PointGeometry)
        self.rb.setColor(QT_RED)
        self.rl = QgsRubberBand(canvas, QgsWkbTypes.LineGeometry)
        self.rl.setColor(QT_RED)

    def canvasPressEvent(self, event):
        if not self.pressed:
            self.pressed = True
            self.point0  = self.toMapCoordinates(event.pos())
            self.rb.addPoint(self.point0)

    def canvasMoveEvent(self, event):
        if self.pressed:
            self.point1 = self.toMapCoordinates(event.pos())
            self.rl.reset(QgsWkbTypes.LineGeometry)
            self.rl.addPoint(self.point0)
            self.rl.addPoint(self.point1)
            self.has_line = True

    def canvasReleaseEvent(self, event):
        self.pressed  = False
        self.has_line = False

        if not self.point0:
            return
        if not self.point1:
            self.point1 = self.point0

        self.open_url()

        self.rb.reset()
        self.rl.reset()
        self.canvas.unsetMapTool(self)

    def deactivate(self):
        """Wywoływane przez QGIS gdy inny map tool przejmuje canvas.
        Czyści rubber bandy i resetuje stan — bez tego gumki zostają
        na mapie, a stan pressed/point0 może zainfekować kolejne wywołanie.
        """
        self.pressed  = False
        self.has_line = False
        self.point0   = None
        self.point1   = None
        self.rb.reset()
        self.rl.reset()
        super().deactivate()

    # -- helpers -----------------------------------------------------------

    def _get_transform(self, target_crs_authid):
        source_crs = self.canvas.mapSettings().destinationCrs()
        dest_crs   = QgsCoordinateReferenceSystem(target_crs_authid)
        return QgsCoordinateTransform(source_crs, dest_crs, QgsProject.instance())

    def _get_angle(self):
        angle = math.atan2(
            self.point1.x() - self.point0.x(),
            self.point1.y() - self.point0.y()
        )
        return math.degrees(angle) if angle > 0 else (math.degrees(angle) + 180) + 180

    def _calculate_zoom(self):
        scale = self.canvas.scale()
        if scale <= 0:
            return 18
        return int(max(0, min(21, math.log2(591657550.5 / scale))))

    def open_url(self):
        target_crs_authid = self.portal_config.get('crs', 'EPSG:4326')
        url_template      = self.portal_config.get('url')

        if not url_template:
            return

        transform = self._get_transform(target_crs_authid)
        pt        = transform.transform(self.point0)
        angle     = self._get_angle()

        if self.dynamic_mode:
            zoom  = self._calculate_zoom()
            scale = round(self.canvas.scale())

            transformed_extent = transform.transformBoundingBox(
                self.canvas.extent()
            )
            xmin = transformed_extent.xMinimum()
            ymin = transformed_extent.yMinimum()
            xmax = transformed_extent.xMaximum()
            ymax = transformed_extent.yMaximum()
        else:
            zoom  = 19
            scale = 2000
            xmin  = pt.x() - 100
            ymin  = pt.y() - 100
            xmax  = pt.x() + 100
            ymax  = pt.y() + 100

        params = {
            'x': pt.x(), 'y': pt.y(),
            'lat': pt.y(), 'lon': pt.x(),
            'angle': angle,
            'zoom': zoom, 'scale': scale,
            'xmin': xmin, 'ymin': ymin,
            'xmax': xmax, 'ymax': ymax,
        }

        try:
            url = url_template.format(**params)
            QgsMessageLog.logMessage(f"Opening URL: {url}", "PowerPin")
            webbrowser.open_new(url)
        except Exception as e:
            QgsMessageLog.logMessage(
                f"Error formatting URL for {self.portal_config.get('id')}: {e}",
                "PowerPin", Qgis.Warning
            )