# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PowerPinDockWidget
                                 A QGIS plugin
 Plugin eksportuje pinezkę do serwisów typu geoportal.
 Plugin exports pin to popular geoportal-like services.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-15
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Łukasz Świątek
        email                : lukasz.swiatek1996@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import Qt, pyqtSignal

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'power_pin_dockwidget_base.ui'))

# Qt6 przeniosło enumeracje do klas zagnieżdżonych.
# _qt_enum szuka kolejno: nowy styl (PyQt6) → stary styl (PyQt5).
def _qt_enum(cls, *names):
    for name in names:
        val = cls
        for part in name.split('.'):
            val = getattr(val, part, None)
            if val is None:
                break
        if val is not None:
            return val
    raise AttributeError(f"Nie znaleziono enuma {names} na {cls}")

QT_CLICK_FOCUS = _qt_enum(Qt, 'FocusPolicy.ClickFocus', 'ClickFocus')

_DW = QtWidgets.QDockWidget
QT_DW_MOVABLE  = _qt_enum(_DW, 'DockWidgetFeature.DockWidgetMovable',  'DockWidgetMovable')
QT_DW_CLOSABLE = _qt_enum(_DW, 'DockWidgetFeature.DockWidgetClosable', 'DockWidgetClosable')

QT_NO_EDIT = _qt_enum(
    QtWidgets.QAbstractItemView,
    'EditTrigger.NoEditTriggers', 'NoEditTriggers'
)


class PowerPinDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super().__init__(parent)
        self.setupUi(self)

        # Checkboxy (cb_dynamic_view, cb_compact_mode) są zdefiniowane
        # bezpośrednio w pliku .ui — nie tworzymy ich tutaj programowo.

        # Dock nie przechwytuje focusu globalnie — kluczowe dla współpracy
        # z map tools innych wtyczek (np. narzędzia wskazywania punktu).
        self.setFocusPolicy(QT_CLICK_FOCUS)

        # Ogranicz funkcje docku — usuwa dodatkowe ścieżki propagacji zdarzeń
        self.setFeatures(QT_DW_MOVABLE | QT_DW_CLOSABLE)

        # Zabezpieczenie: jawna inicjalizacja na wypadek przeładowania .ui
        self.listWidget.setFocusPolicy(QT_CLICK_FOCUS)
        self.listWidget.setEditTriggers(QT_NO_EDIT)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()